const plantData = [
  {
    name: "Tomato",
    image: "implants/tomato.jpg",
    scientific: "Solanum lycopersicum",
    type: "Vegetable",
    climate: "20–27°C, warm season",
    soil: "Loamy, pH 6–6.8",
    water: "Regular watering",
    nutrients: "NPK fertilizers, compost",
    duration: "60–85 days",
    pests: "Aphids, blight",
    practices: "30-45 cm spacing, proper staking",
    yield: "~25 tons/acre",
    harvest: "Harvest when fruit is red and firm",
    storage: "Cool, dry storage",
    plantSpacing: "30–45 cm",
    wateringSchedule: "Every 2–3 days or when soil is dry",
    farmingProcedure:
      "Prepare raised beds with compost. Transplant seedlings after 25 days. Stake plants. Apply mulch. Prune suckers. Fertilize every 15–20 days. Harvest in 60–85 days.",
    precautions:
      "Avoid overwatering. Monitor for fungal diseases. Use neem spray or organic pesticides.",
  },
  {
    name: "Brinjal",
    image: "implants/brinjal.jpg",
    scientific: "Solanum melongena",
    type: "Vegetable",
    climate: "25–30°C",
    soil: "Well-drained, sandy loam",
    water: "Moderate",
    nutrients: "Compost, NPK",
    duration: "100–150 days",
    pests: "Shoot borers, wilt",
    practices: "Stake plants, avoid waterlogging",
    yield: "20 tons/acre",
    harvest: "Glossy and full-sized fruits",
    storage: "Cool storage",
    plantSpacing: "60 cm × 60 cm",
    wateringSchedule: "Twice a week",
    farmingProcedure:
      "Prepare beds. Transplant after 4-5 weeks. Provide support. Apply fertilizer monthly. Harvest begins after 90–100 days.",
    precautions:
      "Remove infested fruits. Avoid overhead irrigation. Practice crop rotation.",
  },
  {
    name: "Rice",
    image: "implants/rice.jpg",
    scientific: "Oryza sativa",
    type: "Cereal",
    climate: "20–35°C, warm and humid",
    soil: "Clayey loam, pH 5.5–7",
    water: "Flooded fields, high water requirement",
    nutrients: "Urea, DAP, Potash",
    duration: "90–150 days",
    pests: "Stem borers, blast",
    practices: "Transplanting, puddling",
    yield: "2–4 tons/acre",
    harvest: "Grains harden and turn golden",
    storage: "Dry and ventilated silos",
    plantSpacing: "20 × 15 cm (row × plant)",
    wateringSchedule: "Field must be flooded 3–5 cm deep constantly",
    farmingProcedure:
      "Nursery sowing → Transplanting → Weed control → Regular irrigation → Top dressing → Harvest",
    precautions:
      "Use certified seeds. Maintain water level. Control pests early.",
  },
  {
    name: "Wheat",
    image: "implants/wheat.jpg",
    scientific: "Triticum aestivum",
    type: "Cereal",
    climate: "10–25°C, cool and dry",
    soil: "Loamy, pH 6–7.5",
    water: "Moderate, avoid waterlogging",
    nutrients: "NPK fertilizers",
    duration: "100–120 days",
    pests: "Rust, termites",
    practices: "Timely sowing, weed control",
    yield: "3–5 tons/acre",
    harvest: "Grains hard and dry",
    storage: "Dry and sealed bags",
    plantSpacing: "20 cm between rows",
    wateringSchedule: "Every 15–20 days depending on soil moisture",
    farmingProcedure:
      "Ploughing → Sowing → Irrigation → Weed & pest management → Harvest after grains mature",
    precautions:
      "Avoid late sowing. Use rust-resistant varieties. Irrigate at critical stages.",
  },
  {
    name: "Sugarcane",
    image: "implants/sugarcane.jpg",
    scientific: "Saccharum officinarum",
    type: "Cash crop",
    climate: "21–27°C, sunny climate",
    soil: "Loamy, well-drained",
    water: "High water needs, regular irrigation",
    nutrients: "Nitrogen-rich fertilizers",
    duration: "10–12 months",
    pests: "Borers, red rot",
    practices: "Deep ploughing, proper spacing",
    yield: "25–50 tons/acre",
    harvest: "When stalks mature and juice is sweet",
    storage: "Process immediately or store in cool sheds",
    plantSpacing: "90 cm × 30 cm",
    wateringSchedule: "Weekly or as needed depending on season",
    farmingProcedure:
      "Soil preparation → Furrow planting → Irrigation → Trash mulching → Earthing up → Harvest after maturity",
    precautions:
      "Ensure proper drainage. Control early borer attacks. Use disease-free setts.",
  },
  {
    name: "Maize",
    image: "implants/maize.jpg",
    scientific: "Zea mays",
    type: "Cereal",
    climate: "21–27°C",
    soil: "Well-drained loamy soil",
    water: "Moderate, avoid standing water",
    nutrients: "Nitrogen-rich compost",
    duration: "90–100 days",
    pests: "Armyworms, stalk borers",
    practices: "Crop rotation, weed control",
    yield: "2.5–4 tons/acre",
    harvest: "Cobs hard and dry",
    storage: "Dry and pest-free storage",
    plantSpacing: "75 cm × 25 cm",
    wateringSchedule: "Every 7–10 days",
    farmingProcedure:
      "Land prep → Seed sowing → Fertilizer application → Pest control → Irrigation → Harvest",
    precautions: "Avoid delayed sowing. Timely weed removal. Use pest traps.",
  },
  {
    name: "Groundnut",
    image: "implants/groundnut.jpg",
    scientific: "Arachis hypogaea",
    type: "Legume",
    climate: "25–30°C, dry climate",
    soil: "Sandy loam, pH 5.5–7",
    water: "Moderate, avoid excess",
    nutrients: "Gypsum, phosphorus",
    duration: "100–120 days",
    pests: "Leaf spot, root rot",
    practices: "Timely sowing, good drainage",
    yield: "1.5–2.5 tons/acre",
    harvest: "Leaves turn yellow, pods mature",
    storage: "Dry pods in jute bags",
    plantSpacing: "30 cm × 10 cm",
    wateringSchedule: "Weekly or depending on soil moisture",
    farmingProcedure:
      "Sow in ridges → Light irrigation → Weed & pest control → Earthing up → Harvest pods",
    precautions:
      "Avoid excess nitrogen. Ensure good sunlight. Use seed treatment.",
  },
  {
    name: "Chickpea",
    image: "implants/chickpea.jpg",
    scientific: "Cicer arietinum",
    type: "Legume",
    climate: "20–25°C",
    soil: "Loamy soil, pH 6–7",
    water: "Low, drought-tolerant",
    nutrients: "Phosphorus, potassium",
    duration: "90–100 days",
    pests: "Pod borer",
    practices: "Sow in winter, row spacing",
    yield: "1–1.5 tons/acre",
    harvest: "Dry and mature pods",
    storage: "Cool and dry containers",
    plantSpacing: "30 cm × 10 cm",
    wateringSchedule: "At sowing and flowering stages only",
    farmingProcedure:
      "Land preparation → Winter sowing → Weed control → No heavy irrigation → Harvest dry pods",
    precautions:
      "Avoid waterlogging. Use pest traps. Seed treatment recommended.",
  },
  {
    name: "Cotton",
    image: "implants/cotton.jpg",
    scientific: "Gossypium hirsutum",
    type: "Cash crop",
    climate: "25–35°C, dry season",
    soil: "Black soil, pH 6–7.5",
    water: "Moderate, avoid excess",
    nutrients: "NPK and micronutrients",
    duration: "150–180 days",
    pests: "Bollworms, aphids",
    practices: "Timely weeding, pest control",
    yield: "1–1.5 tons/acre (lint)",
    harvest: "When bolls burst open",
    storage: "Cool and moisture-free",
    plantSpacing: "75 cm × 30 cm",
    wateringSchedule: "Every 10–12 days during flowering and boll formation",
    farmingProcedure:
      "Deep ploughing → Line sowing → Fertilizer and pest application → Irrigation → Boll harvest",
    precautions:
      "Control bollworms early. Ensure adequate sunlight. Avoid excess nitrogen.",
  },
  {
    name: "Soybean",
    image: "implants/soybean.jpg",
    scientific: "Glycine max",
    type: "Legume",
    climate: "20–30°C",
    soil: "Well-drained loam",
    water: "Moderate",
    nutrients: "Phosphorus, potassium",
    duration: "80–100 days",
    pests: "Leaf-eating caterpillars",
    practices: "Seed treatment, row planting",
    yield: "1–2 tons/acre",
    harvest: "Pods turn yellow and dry",
    storage: "Dry and ventilated sacks",
    plantSpacing: "45 cm × 10 cm",
    wateringSchedule: "During flowering and pod filling stages",
    farmingProcedure:
      "Plough land → Sow seeds → Fertilize → Spray for pests → Harvest dry pods",
    precautions:
      "Avoid sowing in waterlogged fields. Use resistant varieties. Ensure proper drying.",
  },
  {
    name: "Banana",
    image: "implants/banana.jpg",
    scientific: "Musa paradisiaca",
    type: "Fruit",
    climate: "26–30°C, humid",
    soil: "Rich loamy soil",
    water: "High water needs",
    nutrients: "Organic compost, potash",
    duration: "10–12 months",
    pests: "Nematodes, weevils",
    practices: "Suckers planting, support plant",
    yield: "30–40 tons/acre",
    harvest: "Fruits turn slightly yellow",
    storage: "Cool and ventilated",
    plantSpacing: "2 m × 2.5 m",
    wateringSchedule: "Every 7–10 days depending on rainfall",
    farmingProcedure:
      "Prepare pits → Plant suckers → Fertilize → Provide support → Harvest ripe fruits",
    precautions:
      "Avoid water stagnation. Use windbreaks in windy areas. Monitor for pest infestation.",
  },
  {
    name: "Onion",
    image: "implants/onion.jpg",
    scientific: "Allium cepa",
    type: "Vegetable",
    climate: "13–25°C",
    soil: "Well-drained loam",
    water: "Moderate",
    nutrients: "Phosphorus-rich manure",
    duration: "100–120 days",
    pests: "Thrips, leaf blight",
    practices: "Weeding and mulching",
    yield: "10–15 tons/acre",
    harvest: "Leaves dry and fall over",
    storage: "Dry and airy place",
    plantSpacing: "15 cm × 10 cm",
    wateringSchedule: "Every 7–12 days, reduce before harvest",
    farmingProcedure:
      "Prepare beds → Sow seeds → Thin seedlings → Fertilize → Harvest mature bulbs",
    precautions:
      "Avoid waterlogging. Stop irrigation before harvest to improve storage life.",
  },
  {
    name: "Potato",
    image: "implants/potato.jpg",
    scientific: "Solanum tuberosum",
    type: "Vegetable",
    climate: "15–25°C",
    soil: "Well-drained sandy loam",
    water: "Moderate",
    nutrients: "Potassium and phosphorus",
    duration: "90–120 days",
    pests: "Blight, nematodes",
    practices: "Hilling, pest control",
    yield: "8–12 tons/acre",
    harvest: "Leaves yellow and die",
    storage: "Cool, dark storage",
    plantSpacing: "60 cm × 20 cm",
    wateringSchedule: "Every 10 days until maturity",
    farmingProcedure:
      "Plough land → Plant tubers → Hill soil → Spray pesticides → Harvest after yellowing",
    precautions:
      "Avoid overwatering. Practice crop rotation to prevent disease.",
  },
  {
    name: "Carrot",
    image: "implants/carrot.jpg",
    scientific: "Daucus carota",
    type: "Vegetable",
    climate: "16–24°C",
    soil: "Loose, sandy loam",
    water: "Frequent light watering",
    nutrients: "Compost-rich soil",
    duration: "70–90 days",
    pests: "Root flies",
    practices: "Thin sowing, no waterlogging",
    yield: "8–10 tons/acre",
    harvest: "Roots reach desired size",
    storage: "Refrigerated or root cellars",
    plantSpacing: "30 cm × 5 cm",
    wateringSchedule: "Light watering every 4–5 days",
    farmingProcedure:
      "Prepare fine soil → Sow seeds → Thin plants → Water regularly → Harvest mature roots",
    precautions:
      "Avoid hard soil. Ensure proper thinning to avoid deformation.",
  },
  {
    name: "Cauliflower",
    image: "implants/cauliflower.jpg",
    scientific: "Brassica oleracea var. botrytis",
    type: "Vegetable",
    climate: "18–25°C",
    soil: "Fertile loamy soil",
    water: "Regular watering",
    nutrients: "Nitrogen and boron",
    duration: "90–120 days",
    pests: "Cabbage worms, aphids",
    practices: "Mulching, pest control",
    yield: "8–12 tons/acre",
    harvest: "Compact white heads",
    storage: "Cool, humid storage",
    plantSpacing: "45 cm × 45 cm",
    wateringSchedule: "Weekly or as needed to maintain moisture",
    farmingProcedure:
      "Transplant seedlings → Apply fertilizer → Control pests → Harvest mature heads",
    precautions:
      "Ensure proper spacing. Avoid overhead irrigation to prevent disease.",
  },
  {
    name: "Cabbage",
    image: "implants/cabbage.jpg",
    scientific: "Brassica oleracea var. capitata",
    type: "Vegetable",
    climate: "15–20°C",
    soil: "Sandy loam, pH 6–6.5",
    water: "Consistent moisture",
    nutrients: "Organic matter, nitrogen",
    duration: "80–100 days",
    pests: "Loopers, cutworms",
    practices: "Proper spacing and pest checks",
    yield: "10–15 tons/acre",
    harvest: "Firm and mature heads",
    storage: "Cold storage",
    plantSpacing: "45 cm × 45 cm",
    wateringSchedule: "Every 5–7 days",
    farmingProcedure:
      "Transplant seedlings → Fertilize → Monitor pests → Harvest mature heads",
    precautions: "Avoid excessive nitrogen. Rotate crops to avoid disease.",
  },
  {
    name: "Mango",
    image: "implants/mango.jpg",
    scientific: "Mangifera indica",
    type: "Fruit",
    climate: "24–30°C, tropical/subtropical",
    soil: "Well-drained loamy soil",
    water: "Moderate, avoid waterlogging",
    nutrients: "Compost, potassium fertilizers",
    duration: "3–5 years (fruiting)",
    pests: "Fruit flies, mealybugs",
    practices: "Regular pruning, mulching",
    yield: "4–6 tons/acre (mature trees)",
    harvest: "Fruits change color and soften",
    storage: "Cool, well-ventilated rooms",
    plantSpacing: "8 m × 8 m",
    wateringSchedule: "Once a week during flowering and fruiting",
    farmingProcedure:
      "Plant grafts → Irrigate and fertilize → Prune annually → Protect fruits → Harvest ripened fruits",
    precautions: "Avoid overwatering. Use fruit fly traps.",
  },
  {
    name: "Papaya",
    image: "implants/papaya.jpg",
    scientific: "Carica papaya",
    type: "Fruit",
    climate: "25–35°C, warm climate",
    soil: "Well-drained sandy loam",
    water: "Regular, drip irrigation preferred",
    nutrients: "Organic manure, NPK",
    duration: "6–9 months",
    pests: "Aphids, root rot",
    practices: "Spacing 1.5–2 m, remove male plants",
    yield: "30–50 tons/acre",
    harvest: "Fruits turn yellowish",
    storage: "Short term in cool storage",
    plantSpacing: "2 m × 2 m",
    wateringSchedule: "Twice a week or drip daily",
    farmingProcedure:
      "Plant seedlings → Fertilize → Weed control → Remove male plants → Harvest mature fruits",
    precautions:
      "Avoid frost-prone areas. Ensure male plant removal to boost yield.",
  },
  {
    name: "Pomegranate",
    image: "implants/pomegranate.jpg",
    scientific: "Punica granatum",
    type: "Fruit",
    climate: "25–35°C, arid/semi-arid",
    soil: "Well-drained loamy soil",
    water: "Moderate",
    nutrients: "Farmyard manure, boron",
    duration: "8–10 months (bearing starts 2–3 years)",
    pests: "Fruit borer, aphids",
    practices: "Pruning, pest monitoring",
    yield: "10–12 tons/acre",
    harvest: "Fruits turn red and firm",
    storage: "Refrigerated for longer life",
    plantSpacing: "5 m × 5 m",
    wateringSchedule: "Every 10–15 days",
    farmingProcedure:
      "Plant saplings → Prune branches → Apply fertilizer → Monitor for pests → Harvest ripe fruits",
    precautions:
      "Avoid overirrigation. Ensure sunlight exposure for good fruit quality.",
  },
  {
    name: "Guava",
    image: "implants/guava.jpg",
    scientific: "Psidium guajava",
    type: "Fruit",
    climate: "23–28°C",
    soil: "Sandy loam, pH 5.5–7",
    water: "Low to moderate",
    nutrients: "NPK, organic manure",
    duration: "2–3 years for bearing",
    pests: "Fruit flies, scale insects",
    practices: "Prune annually, irrigate during flowering",
    yield: "8–12 tons/acre",
    harvest: "Fruits firm and aromatic",
    storage: "Cool, ventilated place",
    plantSpacing: "6 m × 6 m",
    wateringSchedule: "Monthly or during dry spells",
    farmingProcedure:
      "Plant grafts → Prune annually → Apply manure → Harvest mature fruits",
    precautions:
      "Avoid excessive irrigation. Monitor for fruit flies during ripening stage.",
  },
  {
    name: "Turmeric",
    image: "implants/turmeric.jpg",
    scientific: "Curcuma longa",
    type: "Spice",
    climate: "20–30°C, humid",
    soil: "Loamy soil, well-drained",
    water: "Regular moist conditions",
    nutrients: "Compost, potash",
    duration: "7–9 months",
    pests: "Rhizome rot, leaf blotch",
    practices: "Rhizome treatment, mulching",
    yield: "6–8 tons/acre",
    harvest: "Leaves dry and fall",
    storage: "Dried and stored in sacks",
    plantSpacing: "30 cm × 25 cm",
    wateringSchedule: "Every 7–10 days depending on rainfall",
    farmingProcedure:
      "Prepare raised beds → Plant rhizomes → Mulch → Irrigate → Harvest when leaves dry",
    precautions:
      "Avoid water stagnation. Use disease-free rhizomes. Maintain soil moisture.",
  },
  {
    name: "Ginger",
    image: "implants/ginger.jpg",
    scientific: "Zingiber officinale",
    type: "Spice",
    climate: "25–30°C, moist and warm",
    soil: "Loamy, rich in organic matter",
    water: "Moderate and frequent",
    nutrients: "Farmyard manure, NPK",
    duration: "8–10 months",
    pests: "Rhizome rot, nematodes",
    practices: "Seed rhizome treatment",
    yield: "6–10 tons/acre",
    harvest: "Leaves turn yellow and dry",
    storage: "Dried rhizomes in sacks",
    plantSpacing: "30 cm × 20 cm",
    wateringSchedule: "Once a week or based on moisture level",
    farmingProcedure:
      "Prepare beds → Sow treated rhizomes → Apply mulch → Irrigate → Harvest mature rhizomes",
    precautions:
      "Avoid waterlogging. Use well-rotted compost. Monitor for fungal diseases.",
  },
  {
    name: "Spinach",
    image: "implants/spinach.jpg",
    scientific: "Spinacia oleracea",
    type: "Leafy vegetable",
    climate: "15–25°C",
    soil: "Loamy soil, well-drained",
    water: "Frequent light watering",
    nutrients: "Compost, nitrogen",
    duration: "30–45 days",
    pests: "Leaf miners, aphids",
    practices: "Succession planting every 2 weeks",
    yield: "4–6 tons/acre",
    harvest: "Tender, dark green leaves",
    storage: "Cool and moist area",
    plantSpacing: "20 cm × 10 cm",
    wateringSchedule: "Every 2–3 days",
    farmingProcedure:
      "Till soil → Sow seeds → Water frequently → Harvest tender leaves",
    precautions: "Avoid overwatering. Thin seedlings to prevent overcrowding.",
  },
  {
    name: "Lady Finger",
    image: "implants/ladyfinger.jpg",
    scientific: "Abelmoschus esculentus",
    type: "Vegetable",
    climate: "25–35°C",
    soil: "Well-drained loamy soil",
    water: "Moderate",
    nutrients: "Compost, NPK",
    duration: "50–60 days",
    pests: "Fruit borers, aphids",
    practices: "Spacing 30 cm, pluck regularly",
    yield: "6–8 tons/acre",
    harvest: "Young and tender pods",
    storage: "Cool and dry storage",
    plantSpacing: "30 cm × 30 cm",
    wateringSchedule: "Twice a week",
    farmingProcedure:
      "Plough land → Sow seeds → Weed regularly → Spray for pests → Harvest tender pods",
    precautions: "Harvest on time. Avoid waterlogging. Monitor pest attacks.",
  },
  {
    name: "Fenugreek",
    image: "implants/fenugreek.jpg",
    scientific: "Trigonella foenum-graecum",
    type: "Leafy vegetable/Spice",
    climate: "10–25°C",
    soil: "Loamy soil",
    water: "Moderate",
    nutrients: "Organic manure",
    duration: "30–40 days for leaves, 90 days for seeds",
    pests: "Aphids, powdery mildew",
    practices: "Sow in rows, frequent harvesting",
    yield: "2–3 tons/acre (seeds)",
    harvest: "Leaves before flowering; seeds when dry",
    storage: "Dry leaves/seeds in airtight containers",
    plantSpacing: "20 cm × 10 cm",
    wateringSchedule: "Every 5–7 days",
    farmingProcedure:
      "Prepare beds → Sow seeds → Water regularly → Harvest leaves/seeds",
    precautions:
      "Ensure good air circulation. Harvest before seed formation for leaves.",
  },
  {
    name: "Mustard",
    image: "implants/mustard.jpg",
    scientific: "Brassica juncea",
    type: "Oilseed",
    climate: "15–25°C, cool season",
    soil: "Loamy, pH 6–7",
    water: "Low to moderate",
    nutrients: "Phosphorus and sulfur",
    duration: "90–100 days",
    pests: "Aphids, white rust",
    practices: "Timely sowing and weeding",
    yield: "1–1.5 tons/acre",
    harvest: "Pods turn yellow and dry",
    storage: "Cool and dry storage",
    plantSpacing: "30 cm × 10 cm",
    wateringSchedule: "Once every 10–12 days",
    farmingProcedure:
      "Plough land → Sow seeds → Fertilize → Control pests → Harvest dry pods",
    precautions: "Avoid excessive moisture. Use disease-resistant varieties.",
  },
  {
    name: "Sorghum",
    image: "implants/sorghum.jpg",
    scientific: "Sorghum bicolor",
    type: "Cereal",
    climate: "25–32°C, semi-arid regions",
    soil: "Well-drained loamy soil",
    water: "Low to moderate, drought-tolerant",
    nutrients: "Nitrogen and phosphorus fertilizers",
    duration: "100–120 days",
    pests: "Shoot fly, stem borer",
    practices: "Timely sowing, crop rotation",
    yield: "1–1.5 tons/acre",
    harvest: "Grains harden and turn reddish-brown",
    storage: "Dry and ventilated storage",
    plantSpacing: "45 cm × 15 cm",
    wateringSchedule: "Irrigate only during dry spells",
    farmingProcedure:
      "Prepare soil → Sow seeds → Weed and fertilize → Harvest mature grains",
    precautions: "Avoid overwatering. Rotate crops to prevent pest buildup.",
  },
  {
    name: "Pearl Millet",
    image: "implants/pearl_millet.jpg",
    scientific: "Pennisetum glaucum",
    type: "Cereal",
    climate: "25–35°C, arid and semi-arid regions",
    soil: "Sandy loam, well-drained",
    water: "Low, highly drought-tolerant",
    nutrients: "Organic manure, nitrogen fertilizers",
    duration: "80–90 days",
    pests: "Downy mildew, stem borer",
    practices: "Thinning, timely weeding",
    yield: "0.8–1.2 tons/acre",
    harvest: "Grains harden and panicles dry",
    storage: "Dry and pest-free storage",
    plantSpacing: "45 cm × 10 cm",
    wateringSchedule: "Only during prolonged drought",
    farmingProcedure:
      "Plough land → Sow seeds → Weed and thin → Harvest dry panicles",
    precautions: "Use mildew-resistant varieties. Avoid overwatering.",
  },
  {
    name: "Barley",
    image: "implants/barley.jpg",
    scientific: "Hordeum vulgare",
    type: "Cereal",
    climate: "12–18°C, cool and dry",
    soil: "Light to medium loam",
    water: "Low to moderate",
    nutrients: "Nitrogen and phosphorus fertilizers",
    duration: "120–150 days",
    pests: "Aphids, rust",
    practices: "Early sowing, proper drainage",
    yield: "1.5–2 tons/acre",
    harvest: "Grains hard and golden",
    storage: "Dry and cool storage",
    plantSpacing: "20 cm × 5 cm",
    wateringSchedule: "Irrigate at tillering and heading stages",
    farmingProcedure:
      "Prepare field → Sow → Apply fertilizer → Irrigate → Harvest ripe grains",
    precautions: "Avoid waterlogging. Use rust-resistant varieties.",
  },
  {
    name: "Sesame",
    image: "implants/sesame.jpg",
    scientific: "Sesamum indicum",
    type: "Oilseed",
    climate: "25–30°C, warm and dry",
    soil: "Well-drained sandy loam",
    water: "Low, drought-tolerant",
    nutrients: "Phosphorus and potassium",
    duration: "80–90 days",
    pests: "Leaf roller, gall fly",
    practices: "Thin sowing, timely weeding",
    yield: "0.3–0.5 tons/acre",
    harvest: "Capsules turn yellow and dry",
    storage: "Dry and ventilated storage",
    plantSpacing: "30 cm × 10 cm",
    wateringSchedule: "Only if rainfall is inadequate",
    farmingProcedure:
      "Prepare land → Sow seeds → Weed regularly → Harvest dry capsules",
    precautions: "Do not irrigate during flowering. Harvest before shattering.",
  },
  {
    name: "Sunflower",
    image: "implants/sunflower.jpg",
    scientific: "Helianthus annuus",
    type: "Oilseed",
    climate: "20–25°C, sunny conditions",
    soil: "Loamy, well-drained",
    water: "Moderate",
    nutrients: "Nitrogen, phosphorus, potassium",
    duration: "90–120 days",
    pests: "Head borer, leaf miner",
    practices: "Proper spacing, pest monitoring",
    yield: "0.8–1.2 tons/acre",
    harvest: "Back of flower head turns yellow-brown",
    storage: "Dry and cool storage",
    plantSpacing: "60 cm × 30 cm",
    wateringSchedule: "Weekly if rainfall is low",
    farmingProcedure:
      "Prepare soil → Sow seeds → Monitor pests → Harvest when heads dry",
    precautions: "Avoid waterlogging. Ensure full sun exposure.",
  },
  {
    name: "Linseed",
    image: "implants/linseed.jpg",
    scientific: "Linum usitatissimum",
    type: "Oilseed",
    climate: "15–25°C, cool and dry",
    soil: "Clay loam, well-drained",
    water: "Low to moderate",
    nutrients: "Phosphorus and potassium",
    duration: "120–130 days",
    pests: "Aphids, powdery mildew",
    practices: "Early sowing, crop rotation",
    yield: "0.4–0.6 tons/acre",
    harvest: "Capsules turn brown and dry",
    storage: "Dry and ventilated storage",
    plantSpacing: "20 cm × 10 cm",
    wateringSchedule: "Minimal; irrigate only during dry spells",
    farmingProcedure:
      "Plow field → Sow → Weed as needed → Harvest mature capsules",
    precautions: "Avoid excessive irrigation. Rotate crops annually.",
  },
  {
    name: "Safflower",
    image: "implants/safflower.jpg",
    scientific: "Carthamus tinctorius",
    type: "Oilseed",
    climate: "24–32°C, arid regions",
    soil: "Well-drained loamy soil",
    water: "Low, drought-tolerant",
    nutrients: "Nitrogen and phosphorus",
    duration: "120–150 days",
    pests: "Aphids, leaf spot",
    practices: "Wide spacing, timely weeding",
    yield: "0.5–0.7 tons/acre",
    harvest: "Heads turn brown and dry",
    storage: "Dry and pest-free storage",
    plantSpacing: "45 cm × 20 cm",
    wateringSchedule: "Only if severe drought",
    farmingProcedure: "Prepare land → Sow → Weed → Harvest dry heads",
    precautions: "Avoid overwatering. Watch for early aphid attacks.",
  },
  {
    name: "Jute",
    image: "implants/jute.jpg",
    scientific: "Corchorus olitorius",
    type: "Fiber crop",
    climate: "24–37°C, warm and humid",
    soil: "Alluvial, well-drained",
    water: "High, requires ample rainfall",
    nutrients: "Nitrogen, phosphorus, potassium",
    duration: "120–150 days",
    pests: "Stem rot, mite",
    practices: "Dense sowing, retting after harvest",
    yield: "1.5–2 tons/acre",
    harvest: "Plants start shedding leaves",
    storage: "Dry and cool storage",
    plantSpacing: "20 cm × 5 cm",
    wateringSchedule: "Ensure sufficient moisture during early growth",
    farmingProcedure:
      "Level field → Sow → Irrigate as needed → Ret after harvest",
    precautions: "Maintain proper retting time. Avoid stagnant water.",
  },
  {
    name: "Tea",
    image: "implants/tea.jpg",
    scientific: "Camellia sinensis",
    type: "Beverage crop",
    climate: "20–30°C, humid and rainy",
    soil: "Acidic, well-drained loamy soil",
    water: "High, requires frequent rainfall",
    nutrients: "Nitrogen-rich fertilizers",
    duration: "3–5 years to first harvest",
    pests: "Tea mosquito bug, red spider mite",
    practices: "Pruning, shade management",
    yield: "1000–2000 kg/acre (made tea)",
    harvest: "Plucked every 7–10 days (tender leaves)",
    storage: "Dried and processed; moisture-free storage",
    plantSpacing: "100 cm × 75 cm",
    wateringSchedule: "Frequent light irrigation if rainfall is insufficient",
    farmingProcedure:
      "Plant saplings → Prune regularly → Pluck leaves → Process and store",
    precautions: "Maintain shade. Avoid water stagnation.",
  },
  {
    name: "Coffee",
    image: "implants/coffee.jpg",
    scientific: "Coffea arabica",
    type: "Beverage crop",
    climate: "15–28°C, tropical with some shade",
    soil: "Well-drained, slightly acidic soil",
    water: "Moderate, needs regular rainfall",
    nutrients: "Nitrogen, potassium, phosphorus",
    duration: "3–4 years to yield; 20–25 years lifespan",
    pests: "Coffee borer, white stem borer",
    practices: "Shade management, mulching",
    yield: "600–800 kg/acre",
    harvest: "When berries turn red",
    storage: "Dried beans stored in moisture-free areas",
    plantSpacing: "2 m × 2 m",
    wateringSchedule: "Rain-fed; supplement during dry spells",
    farmingProcedure:
      "Prepare pits → Plant seedlings → Mulch → Harvest red berries → Dry",
    precautions: "Avoid dense shade. Control borers early.",
  },
  {
    name: "Tobacco",
    image: "implants/tobacco.jpg",
    scientific: "Nicotiana tabacum",
    type: "Commercial crop",
    climate: "20–30°C, dry and sunny",
    soil: "Sandy loam, well-drained",
    water: "Moderate, avoid waterlogging",
    nutrients: "Nitrogen-rich fertilizers",
    duration: "100–130 days",
    pests: "Aphids, cutworms",
    practices: "Topping and sucker control",
    yield: "800–1000 kg/acre",
    harvest: "Leaves mature and turn yellowish-green",
    storage: "Cured and stored in dry areas",
    plantSpacing: "60 cm × 30 cm",
    wateringSchedule: "Irrigate lightly at regular intervals",
    farmingProcedure:
      "Transplant seedlings → Remove suckers → Harvest mature leaves → Cure",
    precautions: "Avoid overwatering. Ensure proper curing.",
  },
  {
    name: "Guar (Cluster Bean)",
    image: "implants/guar.jpg",
    scientific: "Cyamopsis tetragonoloba",
    type: "Commercial legume crop",
    climate: "25–35°C, arid regions",
    soil: "Sandy loam, drought-tolerant",
    water: "Low, prefers dry conditions",
    nutrients: "Organic manure, minimal chemical inputs",
    duration: "90–120 days",
    pests: "Leaf spot, pod borer",
    practices: "Weeding, proper spacing",
    yield: "0.8–1.2 tons/acre",
    harvest: "Pods dry and turn straw-colored",
    storage: "Dry and cool storage",
    plantSpacing: "45 cm × 20 cm",
    wateringSchedule: "Rain-fed; irrigate only in extreme drought",
    farmingProcedure: "Plow field → Sow → Weed → Harvest dry pods",
    precautions: "Avoid excess nitrogen. Monitor for pod borers.",
  },
];
